server:
  port: 88

eureka:
  client:                             # 客户端注册进eureka 服务列表
    register-with-eureka: false
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka   # 单机配置 eureka server端设置的defaultZone值（要注册的euraka的defaultZone值）
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka   # 集群配置 eureka server端设置的多个defaultZone值
feign:
  hystrix:
    enabled: true                     # 增加feign的服务降级处理